import { Package, Testimonial, Review, CaseStudy, FAQ } from './types';

export const DOMESTIC_PACKAGES: Package[] = [
  {
    id: 'd1',
    category: 'domestic',
    title: 'Goa Beach Paradise',
    destination: 'Goa',
    duration: '4 Days / 3 Nights',
    price: '₹15,000',
    description: 'Experience the ultimate beach holiday with water sports, nightlife, and serene sunsets.',
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=1964&auto=format&fit=crop',
    rating: 4.8,
    reviews: 124,
    itinerary: [
      { day: 'Day 1', description: 'Arrival in Goa, Check-in to resort, Evening beach walk.' },
      { day: 'Day 2', description: 'North Goa sightseeing: Baga Beach, Fort Aguada.' },
      { day: 'Day 3', description: 'South Goa tour: Colva Beach, Mangueshi Temple, Boat Cruise.' },
      { day: 'Day 4', description: 'Departure from Goa.' },
    ],
    inclusions: ['4-Star Hotel Stay', 'Breakfast & Dinner', 'Airport Transfers', 'Sightseeing'],
    exclusions: ['Flights', 'Lunch', 'Personal Expenses', 'Water sports fees'],
  },
  {
    id: 'd2',
    category: 'domestic',
    title: 'Heavenly Kashmir',
    destination: 'Kashmir',
    duration: '6 Days / 5 Nights',
    price: '₹28,500',
    description: 'Explore the paradise on earth with Shikara rides, snow-capped mountains, and lush valleys.',
    image: 'https://images.unsplash.com/photo-1595815771614-ade9d652a65d?q=80&w=2070&auto=format&fit=crop',
    rating: 4.9,
    reviews: 210,
    itinerary: [
      { day: 'Day 1', description: 'Arrival in Srinagar, Shikara ride on Dal Lake.' },
      { day: 'Day 2', description: 'Excursion to Sonamarg (Meadow of Gold).' },
      { day: 'Day 3', description: 'Gulmarg tour & Gondola ride.' },
      { day: 'Day 4', description: 'Pahalgam (Valley of Shepherds) visit.' },
      { day: 'Day 5', description: 'Local Srinagar sightseeing (Mughal Gardens).' },
      { day: 'Day 6', description: 'Departure.' },
    ],
    inclusions: ['Houseboat Stay', 'Breakfast & Dinner', 'Gondola Ride Phase 1', 'Private Cab'],
    exclusions: ['Flights', 'Lunch', 'Pony Rides', 'Guide fees'],
  },
  {
    id: 'd3',
    category: 'domestic',
    title: 'Royal Rajasthan',
    destination: 'Rajasthan',
    duration: '7 Days / 6 Nights',
    price: '₹32,000',
    description: 'Discover the land of kings with majestic forts, vibrant culture, and desert safaris.',
    image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?q=80&w=2070&auto=format&fit=crop',
    rating: 4.7,
    reviews: 185,
    itinerary: [
      { day: 'Day 1', description: 'Arrival in Jaipur, Chokhi Dhani visit.' },
      { day: 'Day 2', description: 'Jaipur Forts: Amber Fort, Hawa Mahal, City Palace.' },
      { day: 'Day 3', description: 'Transfer to Jodhpur, Mehrangarh Fort.' },
      { day: 'Day 4', description: 'Transfer to Udaipur via Ranakpur.' },
      { day: 'Day 5', description: 'Udaipur City Tour & Lake Pichola boating.' },
      { day: 'Day 6', description: 'Jaisalmer Desert Safari & Camping.' },
      { day: 'Day 7', description: 'Departure.' },
    ],
    inclusions: ['Heritage Hotel Stay', 'Breakfast', 'Desert Safari', 'AC Transfers'],
    exclusions: ['Flights', 'Meals other than breakfast', 'Monument Entry Fees'],
  },
  {
    id: 'd4',
    category: 'domestic',
    title: 'God\'s Own Country',
    destination: 'Kerala',
    duration: '5 Days / 4 Nights',
    price: '₹22,000',
    description: 'Relax in the tranquil backwaters, lush tea gardens, and pristine beaches of Kerala.',
    image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?q=80&w=2069&auto=format&fit=crop',
    rating: 4.8,
    reviews: 156,
    itinerary: [
      { day: 'Day 1', description: 'Arrival in Kochi, Transfer to Munnar.' },
      { day: 'Day 2', description: 'Munnar Tea Gardens & Mattupetty Dam.' },
      { day: 'Day 3', description: 'Thekkady Wildlife Sanctuary.' },
      { day: 'Day 4', description: 'Alleppey Houseboat Stay.' },
      { day: 'Day 5', description: 'Departure from Kochi.' },
    ],
    inclusions: ['4-Star Hotels', 'Breakfast', 'Houseboat Stay with all meals', 'Private Cab'],
    exclusions: ['Flights', 'Entry Fees', 'Ayurvedic Spa'],
  },
  {
    id: 'd5',
    category: 'domestic',
    title: 'Himalayan Retreat',
    destination: 'Himachal Pradesh',
    duration: '6 Days / 5 Nights',
    price: '₹24,500',
    description: 'Experience majestic mountains, lush pine forests, and thrilling adventure sports.',
    image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?q=80&w=2070&auto=format&fit=crop',
    rating: 4.6,
    reviews: 198,
    itinerary: [
      { day: 'Day 1', description: 'Arrival in Shimla, Mall Road evening.' },
      { day: 'Day 2', description: 'Kufri excursion & Shimla sightseeing.' },
      { day: 'Day 3', description: 'Transfer to Manali via Kullu.' },
      { day: 'Day 4', description: 'Solang Valley adventure activities.' },
      { day: 'Day 5', description: 'Rohtang Pass (subject to availability).' },
      { day: 'Day 6', description: 'Departure.' },
    ],
    inclusions: ['3/4-Star Hotels', 'Breakfast & Dinner', 'Private Cab', 'Welcome Drink'],
    exclusions: ['Flights/Trains', 'Adventure Sports Fees', 'Rohtang Pass Permit'],
  },
  {
    id: 'd6',
    category: 'domestic',
    title: 'Exotic Andaman',
    destination: 'Andaman',
    duration: '6 Days / 5 Nights',
    price: '₹35,000',
    description: 'Pristine beaches, crystal clear waters, and world-class scuba diving experiences.',
    image: 'https://images.unsplash.com/photo-1589136777351-fdc9c9cb1504?q=80&w=2070&auto=format&fit=crop',
    rating: 4.9,
    reviews: 142,
    itinerary: [
      { day: 'Day 1', description: 'Arrival at Port Blair, Cellular Jail & Light/Sound Show.' },
      { day: 'Day 2', description: 'Ferry to Havelock Island, Radhanagar Beach.' },
      { day: 'Day 3', description: 'Elephant Beach for Water Sports.' },
      { day: 'Day 4', description: 'Ferry to Neil Island, Bharatpur Beach.' },
      { day: 'Day 5', description: 'Return to Port Blair, Local Shopping.' },
      { day: 'Day 6', description: 'Departure.' },
    ],
    inclusions: ['Beach Resorts', 'Breakfast', 'Ferry Tickets', 'Airport Transfers'],
    exclusions: ['Flights', 'Scuba Diving Fees', 'Lunch & Dinner'],
  }
];

export const INTERNATIONAL_PACKAGES: Package[] = [
  {
    id: 'i1',
    category: 'international',
    title: 'Dazzling Dubai',
    destination: 'Dubai',
    duration: '5 Days / 4 Nights',
    price: '₹45,000',
    description: 'Experience futuristic architecture, luxury shopping, and thrilling desert safaris.',
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?q=80&w=2070&auto=format&fit=crop',
    rating: 4.8,
    reviews: 320,
    itinerary: [
      { day: 'Day 1', description: 'Arrival in Dubai, Dhow Cruise Dinner.' },
      { day: 'Day 2', description: 'Dubai City Tour & Burj Khalifa (124th Floor).' },
      { day: 'Day 3', description: 'Desert Safari with BBQ Dinner & Belly Dance.' },
      { day: 'Day 4', description: 'Abu Dhabi City Tour & Ferrari World.' },
      { day: 'Day 5', description: 'Departure.' },
    ],
    inclusions: ['4-Star Hotel', 'Breakfast & 2 Dinners', 'Dubai Visa', 'Burj Khalifa Tickets', 'Transfers'],
    exclusions: ['Flights', 'Tourism Dirham Fee', 'Personal Expenses'],
  },
  {
    id: 'i2',
    category: 'international',
    title: 'Best of Bali',
    destination: 'Bali',
    duration: '6 Days / 5 Nights',
    price: '₹38,000',
    description: 'Explore lush rice terraces, ancient temples, and vibrant beach clubs.',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=2076&auto=format&fit=crop',
    rating: 4.9,
    reviews: 415,
    itinerary: [
      { day: 'Day 1', description: 'Arrival in Bali, Transfer to Seminyak.' },
      { day: 'Day 2', description: 'Water Sports & Uluwatu Temple Sunset Tour.' },
      { day: 'Day 3', description: 'Transfer to Ubud, Ubud Market & Palace.' },
      { day: 'Day 4', description: 'Kintamani Volcano & Tegalalang Rice Terrace.' },
      { day: 'Day 5', description: 'Nusa Penida Island Day Tour.' },
      { day: 'Day 6', description: 'Departure.' },
    ],
    inclusions: ['Pool Villa/Hotel Stay', 'Breakfast', 'English Speaking Guide', 'Nusa Penida Tour'],
    exclusions: ['Flights', 'Visa on Arrival', 'Lunch & Dinner'],
  },
  {
    id: 'i3',
    category: 'international',
    title: 'Tropical Thailand',
    destination: 'Thailand',
    duration: '5 Days / 4 Nights',
    price: '₹28,000',
    description: 'A perfect mix of bustling city life in Bangkok and pristine beaches in Phuket.',
    image: 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?q=80&w=2039&auto=format&fit=crop',
    rating: 4.7,
    reviews: 512,
    itinerary: [
      { day: 'Day 1', description: 'Arrival in Phuket, Fantasea Show.' },
      { day: 'Day 2', description: 'Phi Phi Island Tour by Speedboat.' },
      { day: 'Day 3', description: 'Flight to Bangkok, City Temple Tour.' },
      { day: 'Day 4', description: 'Safari World and Marine Park.' },
      { day: 'Day 5', description: 'Shopping & Departure.' },
    ],
    inclusions: ['3/4-Star Hotels', 'Breakfast', 'Internal Flight', 'Island Tour with Lunch', 'Airport Transfers'],
    exclusions: ['International Flights', 'Visa fees', 'National Park Fees'],
  },
  {
    id: 'i4',
    category: 'international',
    title: 'Stunning Singapore',
    destination: 'Singapore',
    duration: '5 Days / 4 Nights',
    price: '₹52,000',
    description: 'Discover the Lion City with its futuristic gardens, thrilling theme parks, and clean streets.',
    image: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?q=80&w=1952&auto=format&fit=crop',
    rating: 4.8,
    reviews: 289,
    itinerary: [
      { day: 'Day 1', description: 'Arrival in Singapore, Night Safari.' },
      { day: 'Day 2', description: 'Singapore City Tour & Gardens by the Bay.' },
      { day: 'Day 3', description: 'Sentosa Island Tour (Cable Car, Madame Tussauds).' },
      { day: 'Day 4', description: 'Universal Studios Full Day Tour.' },
      { day: 'Day 5', description: 'Departure.' },
    ],
    inclusions: ['4-Star Hotel', 'Breakfast', 'All Attraction Tickets', 'Singapore Visa', 'Transfers'],
    exclusions: ['Flights', 'Lunch & Dinner', 'Personal Expenses'],
  },
  {
    id: 'i5',
    category: 'international',
    title: 'Magical Maldives',
    destination: 'Maldives',
    duration: '4 Days / 3 Nights',
    price: '₹85,000',
    description: 'The ultimate luxury getaway with overwater villas, private beaches, and crystal clear ocean.',
    image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?q=80&w=2065&auto=format&fit=crop',
    rating: 5.0,
    reviews: 178,
    itinerary: [
      { day: 'Day 1', description: 'Arrival in Male, Speedboat to Resort.' },
      { day: 'Day 2', description: 'Leisure Day / Scuba Diving.' },
      { day: 'Day 3', description: 'Sunset Dolphin Cruise & Spa.' },
      { day: 'Day 4', description: 'Departure.' },
    ],
    inclusions: ['Overwater Villa Stay', 'All-Inclusive Meals (B, L, D)', 'Speedboat Transfers', 'Green Tax'],
    exclusions: ['Flights', 'Motorized Water Sports', 'Spa Treatments'],
  },
  {
    id: 'i6',
    category: 'international',
    title: 'European Escapade',
    destination: 'Europe',
    duration: '10 Days / 9 Nights',
    price: '₹1,45,000',
    description: 'A grand tour across France, Switzerland, and Italy covering iconic landmarks.',
    image: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?q=80&w=2020&auto=format&fit=crop',
    rating: 4.9,
    reviews: 450,
    itinerary: [
      { day: 'Day 1-2', description: 'Paris: Eiffel Tower, Louvre, Seine Cruise.' },
      { day: 'Day 3', description: 'Train to Zurich, Switzerland.' },
      { day: 'Day 4', description: 'Mt. Titlis Excursion & Lucerne City Tour.' },
      { day: 'Day 5', description: 'Interlaken & Jungfraujoch.' },
      { day: 'Day 6', description: 'Train to Venice, Gondola Ride.' },
      { day: 'Day 7', description: 'Florence City Tour.' },
      { day: 'Day 8-9', description: 'Rome: Colosseum, Vatican City.' },
      { day: 'Day 10', description: 'Departure from Rome.' },
    ],
    inclusions: ['3/4-Star Hotels', 'Breakfast', 'Schengen Visa Support', 'Eurail Pass', 'Sightseeing'],
    exclusions: ['Flights', 'Lunch & Dinner', 'City Taxes (paid locally)', 'Visa Fees'],
  }
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 't1',
    name: 'Priya Sharma',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=150&auto=format&fit=crop',
    rating: 5,
    text: 'Our Maldives trip was perfectly planned! From the water villa to the seamless transfers, everything felt luxurious and stress-free. Highly recommend their services.',
  },
  {
    id: 't2',
    name: 'Rahul Verma',
    image: 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?q=80&w=150&auto=format&fit=crop',
    rating: 5,
    text: 'Booked the Europe package for my parents. The 24/7 support provided was incredible. They helped at every step, making it a memorable trip.',
  },
  {
    id: 't3',
    name: 'Ananya Desai',
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=150&auto=format&fit=crop',
    rating: 4,
    text: 'Great experience in Bali! The customized itinerary was exactly what we wanted. A slight delay in one of the pickups, but overall fantastic value for money.',
  },
];

export const CASE_STUDIES: CaseStudy[] = [
  {
    id: 'cs1',
    title: 'Family Vacation Package to Europe',
    image: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?q=80&w=2021&auto=format&fit=crop',
    challenge: 'A family of 6 needed a multi-city Europe tour covering Paris, Swiss, and Rome that caters to both elderly parents and young children.',
    solution: 'Designed a customized 12-day slow-paced itinerary with private wheelchair-accessible vans, centrally located hotels, and pre-booked skip-the-line tickets.',
    results: 'Zero hassle across border crossings, 100% schedule adherence, and highly satisfied family members.',
    feedback: '"They made the impossible seem easy. Traveling with kids and seniors is tough, but their meticulous planning saved us!" - The Kapoor Family',
  },
  {
    id: 'cs2',
    title: 'Corporate Incentive Trip to Dubai',
    image: 'https://images.unsplash.com/photo-1542314831-c6a4d14b4f53?q=80&w=2070&auto=format&fit=crop',
    challenge: 'An IT company wanted to reward 50 top performers with a luxurious 3-day trip to Dubai on a strict corporate budget.',
    solution: 'Negotiated group rates with a 5-star hotel, chartered a private luxury Dhow cruise for a networking dinner, and arranged a private desert safari.',
    results: 'Delivered a premium experience at 15% under budget, boosting employee morale significantly.',
    feedback: '"Flawless execution. Our team felt truly valued. We are booking all future corporate events with them." - HR Director',
  }
];

export const FAQS: FAQ[] = [
  { question: 'How do I book a package?', answer: 'You can book directly via our website by clicking the "Book Now" button on any package. Alternatively, you can call us or message us on WhatsApp given in the contact section.' },
  { question: 'Can I customize my itinerary?', answer: 'Absolutely! Our travel experts can tailor any package to suit your preferences, travel dates, and budget.' },
  { question: 'What payment methods are accepted?', answer: 'We accept credit/debit cards, Net Banking, UPI, and major wallets. We also offer EMI options on select credit cards.' },
  { question: 'Is visa support available?', answer: 'Yes, we provide end-to-end visa assistance for all our international packages, including document verification and appointment scheduling.' },
  { question: 'What cancellation policies apply?', answer: 'Cancellation policies vary depending on the destination and airlines. Generally, full refunds are provided if cancelled 30 days prior. Please refer to the specific package details.' },
];
